const express = require("express");
//It generates the running express application.
const app = express();
const passport = require("passport");
const keys = require("../config/keys.js");
const GoogleStrategy = require("passport-google-oauth20").Strategy;

//const passportgoole = require("passport-google-oauth20").Strategy();
//creates a new instance of google strategy.
//console.developers.google.com
passport.use(
  new GoogleStrategy(
    {
      clientID:
        "746396787265-kq1cpchml63noptk0h8bu48aq2c9c3qb.apps.googleusercontent.com",
      clientSecret: "",
      callbackURL: "https://lpo4z0yn99.sse.codesandbox.io/auth/google/callback"
    },
    //used for identiyfying information
    //beacause of access token we can access users data again in future.
    (accesstoken, refreshtoken, profile, done) => {
      console.log(accesstoken);
      console.log(refreshtoken);
      console.log(profile);
    }
  )
);

app.get(
  "/auth/google",
  passport.authenticate("google", { scope: ["profile", "email"] })
);

// if the user gets directed to this route, the code is generated by then.
app.get("/auth/google/callback", (req, res) => {
  res.send("Successfully signed with google");
});

app.get("/", (req, res) => {
  res.send("Lets Begin");
});

app.listen(8080);
